"""add plant emoji

Revision ID: 4e802675b088
Revises: 4813dc396775
Create Date: 2026-07-12 11:35:04.437535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e802675b088'
down_revision = '4813dc396775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_types', schema=None) as batch_op:
        batch_op.drop_column('emoji')

    # ### end Alembic commands ###
