"""add current plant flag

Revision ID: b3d332decd90
Revises: 4e802675b088
Create Date: 2026-07-13 15:38:59.133271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d332decd90'
down_revision = '4e802675b088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plants', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
